//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("LisaKatherineModel", "FK_tblArticle_tblUsers", "tblUsers", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(LisaKatherine.DataEntitiesRepository.Users), "tblArticle", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(LisaKatherine.DataEntitiesRepository.Articles), true)]
[assembly: EdmRelationshipAttribute("LisaKatherineModel", "FK_tblPhotos_tblUsers", "tblUsers", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(LisaKatherine.DataEntitiesRepository.Users), "tblPhotos", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(LisaKatherine.DataEntitiesRepository.Photos), true)]
[assembly: EdmRelationshipAttribute("LisaKatherineModel", "FK_tblArticle_tblArticleType", "tblArticleType", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(LisaKatherine.DataEntitiesRepository.ArticleTypes), "Articles", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(LisaKatherine.DataEntitiesRepository.Articles), true)]
[assembly: EdmRelationshipAttribute("LisaKatherineModel", "FK_tblArticlePublished_tblArticle", "Articles", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(LisaKatherine.DataEntitiesRepository.Articles), "tblArticlePublished", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(LisaKatherine.DataEntitiesRepository.PublishedArticles), true)]
[assembly: EdmRelationshipAttribute("LisaKatherineModel", "FK_tblArticleType_tblSection", "Section", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(LisaKatherine.DataEntitiesRepository.Section), "ArticleTypes", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(LisaKatherine.DataEntitiesRepository.ArticleTypes), true)]
[assembly: EdmRelationshipAttribute("LisaKatherineModel", "FK_tblFacebookPost_tblArticle", "Articles", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(LisaKatherine.DataEntitiesRepository.Articles), "FacebookPost", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(LisaKatherine.DataEntitiesRepository.FacebookPost), true)]
[assembly: EdmRelationshipAttribute("LisaKatherineModel", "FK_tblFacebookPost_tblFacebookUsers", "FacebookUser", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(LisaKatherine.DataEntitiesRepository.FacebookUser), "FacebookPost", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(LisaKatherine.DataEntitiesRepository.FacebookPost), true)]

#endregion

namespace LisaKatherine.DataEntitiesRepository
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class LisaKatherineEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new LisaKatherineEntities object using the connection string found in the 'LisaKatherineEntities' section of the application configuration file.
        /// </summary>
        public LisaKatherineEntities() : base("name=LisaKatherineEntities", "LisaKatherineEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new LisaKatherineEntities object.
        /// </summary>
        public LisaKatherineEntities(string connectionString) : base(connectionString, "LisaKatherineEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new LisaKatherineEntities object.
        /// </summary>
        public LisaKatherineEntities(EntityConnection connection) : base(connection, "LisaKatherineEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Articles> Articles1
        {
            get
            {
                if ((_Articles1 == null))
                {
                    _Articles1 = base.CreateObjectSet<Articles>("Articles1");
                }
                return _Articles1;
            }
        }
        private ObjectSet<Articles> _Articles1;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Photos> tblPhotos
        {
            get
            {
                if ((_tblPhotos == null))
                {
                    _tblPhotos = base.CreateObjectSet<Photos>("tblPhotos");
                }
                return _tblPhotos;
            }
        }
        private ObjectSet<Photos> _tblPhotos;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Users> Users1
        {
            get
            {
                if ((_Users1 == null))
                {
                    _Users1 = base.CreateObjectSet<Users>("Users1");
                }
                return _Users1;
            }
        }
        private ObjectSet<Users> _Users1;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ArticleTypes> ArticleTypes1
        {
            get
            {
                if ((_ArticleTypes1 == null))
                {
                    _ArticleTypes1 = base.CreateObjectSet<ArticleTypes>("ArticleTypes1");
                }
                return _ArticleTypes1;
            }
        }
        private ObjectSet<ArticleTypes> _ArticleTypes1;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<PublishedArticles> PublishedArticles
        {
            get
            {
                if ((_PublishedArticles == null))
                {
                    _PublishedArticles = base.CreateObjectSet<PublishedArticles>("PublishedArticles");
                }
                return _PublishedArticles;
            }
        }
        private ObjectSet<PublishedArticles> _PublishedArticles;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<FlickrSets> FlickrSets
        {
            get
            {
                if ((_FlickrSets == null))
                {
                    _FlickrSets = base.CreateObjectSet<FlickrSets>("FlickrSets");
                }
                return _FlickrSets;
            }
        }
        private ObjectSet<FlickrSets> _FlickrSets;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Section> Sections
        {
            get
            {
                if ((_Sections == null))
                {
                    _Sections = base.CreateObjectSet<Section>("Sections");
                }
                return _Sections;
            }
        }
        private ObjectSet<Section> _Sections;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<FacebookPost> FacebookPosts
        {
            get
            {
                if ((_FacebookPosts == null))
                {
                    _FacebookPosts = base.CreateObjectSet<FacebookPost>("FacebookPosts");
                }
                return _FacebookPosts;
            }
        }
        private ObjectSet<FacebookPost> _FacebookPosts;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<FacebookUser> FacebookUsers
        {
            get
            {
                if ((_FacebookUsers == null))
                {
                    _FacebookUsers = base.CreateObjectSet<FacebookUser>("FacebookUsers");
                }
                return _FacebookUsers;
            }
        }
        private ObjectSet<FacebookUser> _FacebookUsers;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Articles1 EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToArticles1(Articles articles)
        {
            base.AddObject("Articles1", articles);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblPhotos EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblPhotos(Photos photos)
        {
            base.AddObject("tblPhotos", photos);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Users1 EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUsers1(Users users)
        {
            base.AddObject("Users1", users);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ArticleTypes1 EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToArticleTypes1(ArticleTypes articleTypes)
        {
            base.AddObject("ArticleTypes1", articleTypes);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the PublishedArticles EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPublishedArticles(PublishedArticles publishedArticles)
        {
            base.AddObject("PublishedArticles", publishedArticles);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the FlickrSets EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToFlickrSets(FlickrSets flickrSets)
        {
            base.AddObject("FlickrSets", flickrSets);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Sections EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSections(Section section)
        {
            base.AddObject("Sections", section);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the FacebookPosts EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToFacebookPosts(FacebookPost facebookPost)
        {
            base.AddObject("FacebookPosts", facebookPost);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the FacebookUsers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToFacebookUsers(FacebookUser facebookUser)
        {
            base.AddObject("FacebookUsers", facebookUser);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LisaKatherineModel", Name="Articles")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Articles : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Articles object.
        /// </summary>
        /// <param name="articleId">Initial value of the articleId property.</param>
        /// <param name="dateCreated">Initial value of the dateCreated property.</param>
        /// <param name="isPublished">Initial value of the isPublished property.</param>
        public static Articles CreateArticles(global::System.Int32 articleId, global::System.DateTime dateCreated, global::System.Boolean isPublished)
        {
            Articles articles = new Articles();
            articles.articleId = articleId;
            articles.dateCreated = dateCreated;
            articles.isPublished = isPublished;
            return articles;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 articleId
        {
            get
            {
                return _articleId;
            }
            set
            {
                if (_articleId != value)
                {
                    OnarticleIdChanging(value);
                    ReportPropertyChanging("articleId");
                    _articleId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("articleId");
                    OnarticleIdChanged();
                }
            }
        }
        private global::System.Int32 _articleId;
        partial void OnarticleIdChanging(global::System.Int32 value);
        partial void OnarticleIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String headline
        {
            get
            {
                return _headline;
            }
            set
            {
                OnheadlineChanging(value);
                ReportPropertyChanging("headline");
                _headline = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("headline");
                OnheadlineChanged();
            }
        }
        private global::System.String _headline;
        partial void OnheadlineChanging(global::System.String value);
        partial void OnheadlineChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String strapline
        {
            get
            {
                return _strapline;
            }
            set
            {
                OnstraplineChanging(value);
                ReportPropertyChanging("strapline");
                _strapline = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("strapline");
                OnstraplineChanged();
            }
        }
        private global::System.String _strapline;
        partial void OnstraplineChanging(global::System.String value);
        partial void OnstraplineChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String body
        {
            get
            {
                return _body;
            }
            set
            {
                OnbodyChanging(value);
                ReportPropertyChanging("body");
                _body = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("body");
                OnbodyChanged();
            }
        }
        private global::System.String _body;
        partial void OnbodyChanging(global::System.String value);
        partial void OnbodyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime dateCreated
        {
            get
            {
                return _dateCreated;
            }
            set
            {
                OndateCreatedChanging(value);
                ReportPropertyChanging("dateCreated");
                _dateCreated = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("dateCreated");
                OndateCreatedChanged();
            }
        }
        private global::System.DateTime _dateCreated;
        partial void OndateCreatedChanging(global::System.DateTime value);
        partial void OndateCreatedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> datePublished
        {
            get
            {
                return _datePublished;
            }
            set
            {
                OndatePublishedChanging(value);
                ReportPropertyChanging("datePublished");
                _datePublished = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("datePublished");
                OndatePublishedChanged();
            }
        }
        private Nullable<global::System.DateTime> _datePublished;
        partial void OndatePublishedChanging(Nullable<global::System.DateTime> value);
        partial void OndatePublishedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean isPublished
        {
            get
            {
                return _isPublished;
            }
            set
            {
                OnisPublishedChanging(value);
                ReportPropertyChanging("isPublished");
                _isPublished = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("isPublished");
                OnisPublishedChanged();
            }
        }
        private global::System.Boolean _isPublished;
        partial void OnisPublishedChanging(global::System.Boolean value);
        partial void OnisPublishedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> userid
        {
            get
            {
                return _userid;
            }
            set
            {
                OnuseridChanging(value);
                ReportPropertyChanging("userid");
                _userid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("userid");
                OnuseridChanged();
            }
        }
        private Nullable<global::System.Guid> _userid;
        partial void OnuseridChanging(Nullable<global::System.Guid> value);
        partial void OnuseridChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> articleTypeId
        {
            get
            {
                return _articleTypeId;
            }
            set
            {
                OnarticleTypeIdChanging(value);
                ReportPropertyChanging("articleTypeId");
                _articleTypeId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("articleTypeId");
                OnarticleTypeIdChanged();
            }
        }
        private Nullable<global::System.Int32> _articleTypeId;
        partial void OnarticleTypeIdChanging(Nullable<global::System.Int32> value);
        partial void OnarticleTypeIdChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LisaKatherineModel", "FK_tblArticle_tblUsers", "tblUsers")]
        public Users tblUser
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Users>("LisaKatherineModel.FK_tblArticle_tblUsers", "tblUsers").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Users>("LisaKatherineModel.FK_tblArticle_tblUsers", "tblUsers").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Users> tblUserReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Users>("LisaKatherineModel.FK_tblArticle_tblUsers", "tblUsers");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Users>("LisaKatherineModel.FK_tblArticle_tblUsers", "tblUsers", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LisaKatherineModel", "FK_tblArticle_tblArticleType", "tblArticleType")]
        public ArticleTypes tblArticleType
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ArticleTypes>("LisaKatherineModel.FK_tblArticle_tblArticleType", "tblArticleType").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ArticleTypes>("LisaKatherineModel.FK_tblArticle_tblArticleType", "tblArticleType").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<ArticleTypes> tblArticleTypeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ArticleTypes>("LisaKatherineModel.FK_tblArticle_tblArticleType", "tblArticleType");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<ArticleTypes>("LisaKatherineModel.FK_tblArticle_tblArticleType", "tblArticleType", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LisaKatherineModel", "FK_tblArticlePublished_tblArticle", "tblArticlePublished")]
        public PublishedArticles tblArticlePublished
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PublishedArticles>("LisaKatherineModel.FK_tblArticlePublished_tblArticle", "tblArticlePublished").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PublishedArticles>("LisaKatherineModel.FK_tblArticlePublished_tblArticle", "tblArticlePublished").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<PublishedArticles> tblArticlePublishedReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PublishedArticles>("LisaKatherineModel.FK_tblArticlePublished_tblArticle", "tblArticlePublished");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<PublishedArticles>("LisaKatherineModel.FK_tblArticlePublished_tblArticle", "tblArticlePublished", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LisaKatherineModel", "FK_tblFacebookPost_tblArticle", "FacebookPost")]
        public EntityCollection<FacebookPost> tblFacebookPosts
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<FacebookPost>("LisaKatherineModel.FK_tblFacebookPost_tblArticle", "FacebookPost");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<FacebookPost>("LisaKatherineModel.FK_tblFacebookPost_tblArticle", "FacebookPost", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LisaKatherineModel", Name="ArticleTypes")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ArticleTypes : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ArticleTypes object.
        /// </summary>
        /// <param name="articleTypeId">Initial value of the articleTypeId property.</param>
        public static ArticleTypes CreateArticleTypes(global::System.Int32 articleTypeId)
        {
            ArticleTypes articleTypes = new ArticleTypes();
            articleTypes.articleTypeId = articleTypeId;
            return articleTypes;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 articleTypeId
        {
            get
            {
                return _articleTypeId;
            }
            set
            {
                if (_articleTypeId != value)
                {
                    OnarticleTypeIdChanging(value);
                    ReportPropertyChanging("articleTypeId");
                    _articleTypeId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("articleTypeId");
                    OnarticleTypeIdChanged();
                }
            }
        }
        private global::System.Int32 _articleTypeId;
        partial void OnarticleTypeIdChanging(global::System.Int32 value);
        partial void OnarticleTypeIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String articleTypeName
        {
            get
            {
                return _articleTypeName;
            }
            set
            {
                OnarticleTypeNameChanging(value);
                ReportPropertyChanging("articleTypeName");
                _articleTypeName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("articleTypeName");
                OnarticleTypeNameChanged();
            }
        }
        private global::System.String _articleTypeName;
        partial void OnarticleTypeNameChanging(global::System.String value);
        partial void OnarticleTypeNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> sectionid
        {
            get
            {
                return _sectionid;
            }
            set
            {
                OnsectionidChanging(value);
                ReportPropertyChanging("sectionid");
                _sectionid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("sectionid");
                OnsectionidChanged();
            }
        }
        private Nullable<global::System.Int32> _sectionid;
        partial void OnsectionidChanging(Nullable<global::System.Int32> value);
        partial void OnsectionidChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LisaKatherineModel", "FK_tblArticle_tblArticleType", "Articles")]
        public EntityCollection<Articles> tblArticles
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Articles>("LisaKatherineModel.FK_tblArticle_tblArticleType", "Articles");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Articles>("LisaKatherineModel.FK_tblArticle_tblArticleType", "Articles", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LisaKatherineModel", "FK_tblArticleType_tblSection", "Section")]
        public Section tblSection
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Section>("LisaKatherineModel.FK_tblArticleType_tblSection", "Section").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Section>("LisaKatherineModel.FK_tblArticleType_tblSection", "Section").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Section> tblSectionReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Section>("LisaKatherineModel.FK_tblArticleType_tblSection", "Section");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Section>("LisaKatherineModel.FK_tblArticleType_tblSection", "Section", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LisaKatherineModel", Name="FacebookPost")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class FacebookPost : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new FacebookPost object.
        /// </summary>
        /// <param name="postId">Initial value of the postId property.</param>
        /// <param name="facebookId">Initial value of the facebookId property.</param>
        /// <param name="articleId">Initial value of the articleId property.</param>
        /// <param name="approved">Initial value of the approved property.</param>
        /// <param name="dateAdded">Initial value of the dateAdded property.</param>
        public static FacebookPost CreateFacebookPost(global::System.Int32 postId, global::System.Int64 facebookId, global::System.Int32 articleId, global::System.Boolean approved, global::System.DateTime dateAdded)
        {
            FacebookPost facebookPost = new FacebookPost();
            facebookPost.postId = postId;
            facebookPost.facebookId = facebookId;
            facebookPost.articleId = articleId;
            facebookPost.approved = approved;
            facebookPost.dateAdded = dateAdded;
            return facebookPost;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 postId
        {
            get
            {
                return _postId;
            }
            set
            {
                if (_postId != value)
                {
                    OnpostIdChanging(value);
                    ReportPropertyChanging("postId");
                    _postId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("postId");
                    OnpostIdChanged();
                }
            }
        }
        private global::System.Int32 _postId;
        partial void OnpostIdChanging(global::System.Int32 value);
        partial void OnpostIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 facebookId
        {
            get
            {
                return _facebookId;
            }
            set
            {
                OnfacebookIdChanging(value);
                ReportPropertyChanging("facebookId");
                _facebookId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("facebookId");
                OnfacebookIdChanged();
            }
        }
        private global::System.Int64 _facebookId;
        partial void OnfacebookIdChanging(global::System.Int64 value);
        partial void OnfacebookIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 articleId
        {
            get
            {
                return _articleId;
            }
            set
            {
                OnarticleIdChanging(value);
                ReportPropertyChanging("articleId");
                _articleId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("articleId");
                OnarticleIdChanged();
            }
        }
        private global::System.Int32 _articleId;
        partial void OnarticleIdChanging(global::System.Int32 value);
        partial void OnarticleIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String post
        {
            get
            {
                return _post;
            }
            set
            {
                OnpostChanging(value);
                ReportPropertyChanging("post");
                _post = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("post");
                OnpostChanged();
            }
        }
        private global::System.String _post;
        partial void OnpostChanging(global::System.String value);
        partial void OnpostChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean approved
        {
            get
            {
                return _approved;
            }
            set
            {
                OnapprovedChanging(value);
                ReportPropertyChanging("approved");
                _approved = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("approved");
                OnapprovedChanged();
            }
        }
        private global::System.Boolean _approved;
        partial void OnapprovedChanging(global::System.Boolean value);
        partial void OnapprovedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime dateAdded
        {
            get
            {
                return _dateAdded;
            }
            set
            {
                OndateAddedChanging(value);
                ReportPropertyChanging("dateAdded");
                _dateAdded = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("dateAdded");
                OndateAddedChanged();
            }
        }
        private global::System.DateTime _dateAdded;
        partial void OndateAddedChanging(global::System.DateTime value);
        partial void OndateAddedChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LisaKatherineModel", "FK_tblFacebookPost_tblArticle", "Articles")]
        public Articles tblArticle
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Articles>("LisaKatherineModel.FK_tblFacebookPost_tblArticle", "Articles").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Articles>("LisaKatherineModel.FK_tblFacebookPost_tblArticle", "Articles").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Articles> tblArticleReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Articles>("LisaKatherineModel.FK_tblFacebookPost_tblArticle", "Articles");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Articles>("LisaKatherineModel.FK_tblFacebookPost_tblArticle", "Articles", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LisaKatherineModel", "FK_tblFacebookPost_tblFacebookUsers", "FacebookUser")]
        public FacebookUser tblFacebookUser
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<FacebookUser>("LisaKatherineModel.FK_tblFacebookPost_tblFacebookUsers", "FacebookUser").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<FacebookUser>("LisaKatherineModel.FK_tblFacebookPost_tblFacebookUsers", "FacebookUser").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<FacebookUser> tblFacebookUserReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<FacebookUser>("LisaKatherineModel.FK_tblFacebookPost_tblFacebookUsers", "FacebookUser");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<FacebookUser>("LisaKatherineModel.FK_tblFacebookPost_tblFacebookUsers", "FacebookUser", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LisaKatherineModel", Name="FacebookUser")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class FacebookUser : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new FacebookUser object.
        /// </summary>
        /// <param name="facebookId">Initial value of the facebookId property.</param>
        /// <param name="firstlogin">Initial value of the firstlogin property.</param>
        /// <param name="active">Initial value of the active property.</param>
        /// <param name="posts">Initial value of the posts property.</param>
        public static FacebookUser CreateFacebookUser(global::System.Int64 facebookId, global::System.DateTime firstlogin, global::System.Boolean active, global::System.Int32 posts)
        {
            FacebookUser facebookUser = new FacebookUser();
            facebookUser.facebookId = facebookId;
            facebookUser.firstlogin = firstlogin;
            facebookUser.active = active;
            facebookUser.posts = posts;
            return facebookUser;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 facebookId
        {
            get
            {
                return _facebookId;
            }
            set
            {
                if (_facebookId != value)
                {
                    OnfacebookIdChanging(value);
                    ReportPropertyChanging("facebookId");
                    _facebookId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("facebookId");
                    OnfacebookIdChanged();
                }
            }
        }
        private global::System.Int64 _facebookId;
        partial void OnfacebookIdChanging(global::System.Int64 value);
        partial void OnfacebookIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String accessToken
        {
            get
            {
                return _accessToken;
            }
            set
            {
                OnaccessTokenChanging(value);
                ReportPropertyChanging("accessToken");
                _accessToken = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("accessToken");
                OnaccessTokenChanged();
            }
        }
        private global::System.String _accessToken;
        partial void OnaccessTokenChanging(global::System.String value);
        partial void OnaccessTokenChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String gender
        {
            get
            {
                return _gender;
            }
            set
            {
                OngenderChanging(value);
                ReportPropertyChanging("gender");
                _gender = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("gender");
                OngenderChanged();
            }
        }
        private global::System.String _gender;
        partial void OngenderChanging(global::System.String value);
        partial void OngenderChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime firstlogin
        {
            get
            {
                return _firstlogin;
            }
            set
            {
                OnfirstloginChanging(value);
                ReportPropertyChanging("firstlogin");
                _firstlogin = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("firstlogin");
                OnfirstloginChanged();
            }
        }
        private global::System.DateTime _firstlogin;
        partial void OnfirstloginChanging(global::System.DateTime value);
        partial void OnfirstloginChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> lastlogin
        {
            get
            {
                return _lastlogin;
            }
            set
            {
                OnlastloginChanging(value);
                ReportPropertyChanging("lastlogin");
                _lastlogin = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("lastlogin");
                OnlastloginChanged();
            }
        }
        private Nullable<global::System.DateTime> _lastlogin;
        partial void OnlastloginChanging(Nullable<global::System.DateTime> value);
        partial void OnlastloginChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean active
        {
            get
            {
                return _active;
            }
            set
            {
                OnactiveChanging(value);
                ReportPropertyChanging("active");
                _active = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("active");
                OnactiveChanged();
            }
        }
        private global::System.Boolean _active;
        partial void OnactiveChanging(global::System.Boolean value);
        partial void OnactiveChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 posts
        {
            get
            {
                return _posts;
            }
            set
            {
                OnpostsChanging(value);
                ReportPropertyChanging("posts");
                _posts = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("posts");
                OnpostsChanged();
            }
        }
        private global::System.Int32 _posts;
        partial void OnpostsChanging(global::System.Int32 value);
        partial void OnpostsChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LisaKatherineModel", "FK_tblFacebookPost_tblFacebookUsers", "FacebookPost")]
        public EntityCollection<FacebookPost> tblFacebookPosts
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<FacebookPost>("LisaKatherineModel.FK_tblFacebookPost_tblFacebookUsers", "FacebookPost");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<FacebookPost>("LisaKatherineModel.FK_tblFacebookPost_tblFacebookUsers", "FacebookPost", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LisaKatherineModel", Name="FlickrSets")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class FlickrSets : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new FlickrSets object.
        /// </summary>
        /// <param name="setId">Initial value of the SetId property.</param>
        public static FlickrSets CreateFlickrSets(global::System.Int64 setId)
        {
            FlickrSets flickrSets = new FlickrSets();
            flickrSets.SetId = setId;
            return flickrSets;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 SetId
        {
            get
            {
                return _SetId;
            }
            set
            {
                if (_SetId != value)
                {
                    OnSetIdChanging(value);
                    ReportPropertyChanging("SetId");
                    _SetId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("SetId");
                    OnSetIdChanged();
                }
            }
        }
        private global::System.Int64 _SetId;
        partial void OnSetIdChanging(global::System.Int64 value);
        partial void OnSetIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SetName
        {
            get
            {
                return _SetName;
            }
            set
            {
                OnSetNameChanging(value);
                ReportPropertyChanging("SetName");
                _SetName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SetName");
                OnSetNameChanged();
            }
        }
        private global::System.String _SetName;
        partial void OnSetNameChanging(global::System.String value);
        partial void OnSetNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LisaKatherineModel", Name="Photos")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Photos : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Photos object.
        /// </summary>
        /// <param name="photoId">Initial value of the photoId property.</param>
        /// <param name="isHomePage">Initial value of the isHomePage property.</param>
        public static Photos CreatePhotos(global::System.Int32 photoId, global::System.Boolean isHomePage)
        {
            Photos photos = new Photos();
            photos.photoId = photoId;
            photos.isHomePage = isHomePage;
            return photos;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 photoId
        {
            get
            {
                return _photoId;
            }
            set
            {
                if (_photoId != value)
                {
                    OnphotoIdChanging(value);
                    ReportPropertyChanging("photoId");
                    _photoId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("photoId");
                    OnphotoIdChanged();
                }
            }
        }
        private global::System.Int32 _photoId;
        partial void OnphotoIdChanging(global::System.Int32 value);
        partial void OnphotoIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String alt
        {
            get
            {
                return _alt;
            }
            set
            {
                OnaltChanging(value);
                ReportPropertyChanging("alt");
                _alt = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("alt");
                OnaltChanged();
            }
        }
        private global::System.String _alt;
        partial void OnaltChanging(global::System.String value);
        partial void OnaltChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> width
        {
            get
            {
                return _width;
            }
            set
            {
                OnwidthChanging(value);
                ReportPropertyChanging("width");
                _width = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("width");
                OnwidthChanged();
            }
        }
        private Nullable<global::System.Int32> _width;
        partial void OnwidthChanging(Nullable<global::System.Int32> value);
        partial void OnwidthChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> height
        {
            get
            {
                return _height;
            }
            set
            {
                OnheightChanging(value);
                ReportPropertyChanging("height");
                _height = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("height");
                OnheightChanged();
            }
        }
        private Nullable<global::System.Int32> _height;
        partial void OnheightChanging(Nullable<global::System.Int32> value);
        partial void OnheightChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> uploaded
        {
            get
            {
                return _uploaded;
            }
            set
            {
                OnuploadedChanging(value);
                ReportPropertyChanging("uploaded");
                _uploaded = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("uploaded");
                OnuploadedChanged();
            }
        }
        private Nullable<global::System.DateTime> _uploaded;
        partial void OnuploadedChanging(Nullable<global::System.DateTime> value);
        partial void OnuploadedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean isHomePage
        {
            get
            {
                return _isHomePage;
            }
            set
            {
                OnisHomePageChanging(value);
                ReportPropertyChanging("isHomePage");
                _isHomePage = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("isHomePage");
                OnisHomePageChanged();
            }
        }
        private global::System.Boolean _isHomePage;
        partial void OnisHomePageChanging(global::System.Boolean value);
        partial void OnisHomePageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> userId
        {
            get
            {
                return _userId;
            }
            set
            {
                OnuserIdChanging(value);
                ReportPropertyChanging("userId");
                _userId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("userId");
                OnuserIdChanged();
            }
        }
        private Nullable<global::System.Guid> _userId;
        partial void OnuserIdChanging(Nullable<global::System.Guid> value);
        partial void OnuserIdChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LisaKatherineModel", "FK_tblPhotos_tblUsers", "tblUsers")]
        public Users tblUser
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Users>("LisaKatherineModel.FK_tblPhotos_tblUsers", "tblUsers").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Users>("LisaKatherineModel.FK_tblPhotos_tblUsers", "tblUsers").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Users> tblUserReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Users>("LisaKatherineModel.FK_tblPhotos_tblUsers", "tblUsers");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Users>("LisaKatherineModel.FK_tblPhotos_tblUsers", "tblUsers", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LisaKatherineModel", Name="PublishedArticles")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PublishedArticles : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new PublishedArticles object.
        /// </summary>
        /// <param name="articleId">Initial value of the articleId property.</param>
        /// <param name="dateCreated">Initial value of the dateCreated property.</param>
        /// <param name="isPublished">Initial value of the isPublished property.</param>
        public static PublishedArticles CreatePublishedArticles(global::System.Int32 articleId, global::System.DateTime dateCreated, global::System.Boolean isPublished)
        {
            PublishedArticles publishedArticles = new PublishedArticles();
            publishedArticles.articleId = articleId;
            publishedArticles.dateCreated = dateCreated;
            publishedArticles.isPublished = isPublished;
            return publishedArticles;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 articleId
        {
            get
            {
                return _articleId;
            }
            set
            {
                if (_articleId != value)
                {
                    OnarticleIdChanging(value);
                    ReportPropertyChanging("articleId");
                    _articleId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("articleId");
                    OnarticleIdChanged();
                }
            }
        }
        private global::System.Int32 _articleId;
        partial void OnarticleIdChanging(global::System.Int32 value);
        partial void OnarticleIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String headline
        {
            get
            {
                return _headline;
            }
            set
            {
                OnheadlineChanging(value);
                ReportPropertyChanging("headline");
                _headline = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("headline");
                OnheadlineChanged();
            }
        }
        private global::System.String _headline;
        partial void OnheadlineChanging(global::System.String value);
        partial void OnheadlineChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String strapline
        {
            get
            {
                return _strapline;
            }
            set
            {
                OnstraplineChanging(value);
                ReportPropertyChanging("strapline");
                _strapline = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("strapline");
                OnstraplineChanged();
            }
        }
        private global::System.String _strapline;
        partial void OnstraplineChanging(global::System.String value);
        partial void OnstraplineChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String body
        {
            get
            {
                return _body;
            }
            set
            {
                OnbodyChanging(value);
                ReportPropertyChanging("body");
                _body = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("body");
                OnbodyChanged();
            }
        }
        private global::System.String _body;
        partial void OnbodyChanging(global::System.String value);
        partial void OnbodyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime dateCreated
        {
            get
            {
                return _dateCreated;
            }
            set
            {
                OndateCreatedChanging(value);
                ReportPropertyChanging("dateCreated");
                _dateCreated = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("dateCreated");
                OndateCreatedChanged();
            }
        }
        private global::System.DateTime _dateCreated;
        partial void OndateCreatedChanging(global::System.DateTime value);
        partial void OndateCreatedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> datePublished
        {
            get
            {
                return _datePublished;
            }
            set
            {
                OndatePublishedChanging(value);
                ReportPropertyChanging("datePublished");
                _datePublished = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("datePublished");
                OndatePublishedChanged();
            }
        }
        private Nullable<global::System.DateTime> _datePublished;
        partial void OndatePublishedChanging(Nullable<global::System.DateTime> value);
        partial void OndatePublishedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean isPublished
        {
            get
            {
                return _isPublished;
            }
            set
            {
                OnisPublishedChanging(value);
                ReportPropertyChanging("isPublished");
                _isPublished = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("isPublished");
                OnisPublishedChanged();
            }
        }
        private global::System.Boolean _isPublished;
        partial void OnisPublishedChanging(global::System.Boolean value);
        partial void OnisPublishedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> userid
        {
            get
            {
                return _userid;
            }
            set
            {
                OnuseridChanging(value);
                ReportPropertyChanging("userid");
                _userid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("userid");
                OnuseridChanged();
            }
        }
        private Nullable<global::System.Guid> _userid;
        partial void OnuseridChanging(Nullable<global::System.Guid> value);
        partial void OnuseridChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> articleTypeId
        {
            get
            {
                return _articleTypeId;
            }
            set
            {
                OnarticleTypeIdChanging(value);
                ReportPropertyChanging("articleTypeId");
                _articleTypeId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("articleTypeId");
                OnarticleTypeIdChanged();
            }
        }
        private Nullable<global::System.Int32> _articleTypeId;
        partial void OnarticleTypeIdChanging(Nullable<global::System.Int32> value);
        partial void OnarticleTypeIdChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LisaKatherineModel", "FK_tblArticlePublished_tblArticle", "Articles")]
        public Articles tblArticle
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Articles>("LisaKatherineModel.FK_tblArticlePublished_tblArticle", "Articles").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Articles>("LisaKatherineModel.FK_tblArticlePublished_tblArticle", "Articles").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Articles> tblArticleReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Articles>("LisaKatherineModel.FK_tblArticlePublished_tblArticle", "Articles");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Articles>("LisaKatherineModel.FK_tblArticlePublished_tblArticle", "Articles", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LisaKatherineModel", Name="Section")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Section : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Section object.
        /// </summary>
        /// <param name="sectionId">Initial value of the sectionId property.</param>
        public static Section CreateSection(global::System.Int32 sectionId)
        {
            Section section = new Section();
            section.sectionId = sectionId;
            return section;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 sectionId
        {
            get
            {
                return _sectionId;
            }
            set
            {
                if (_sectionId != value)
                {
                    OnsectionIdChanging(value);
                    ReportPropertyChanging("sectionId");
                    _sectionId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("sectionId");
                    OnsectionIdChanged();
                }
            }
        }
        private global::System.Int32 _sectionId;
        partial void OnsectionIdChanging(global::System.Int32 value);
        partial void OnsectionIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String section
        {
            get
            {
                return _section;
            }
            set
            {
                OnsectionChanging(value);
                ReportPropertyChanging("section");
                _section = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("section");
                OnsectionChanged();
            }
        }
        private global::System.String _section;
        partial void OnsectionChanging(global::System.String value);
        partial void OnsectionChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LisaKatherineModel", "FK_tblArticleType_tblSection", "ArticleTypes")]
        public EntityCollection<ArticleTypes> tblArticleTypes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ArticleTypes>("LisaKatherineModel.FK_tblArticleType_tblSection", "ArticleTypes");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ArticleTypes>("LisaKatherineModel.FK_tblArticleType_tblSection", "ArticleTypes", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LisaKatherineModel", Name="Users")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Users : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Users object.
        /// </summary>
        /// <param name="userId">Initial value of the userId property.</param>
        public static Users CreateUsers(global::System.Guid userId)
        {
            Users users = new Users();
            users.userId = userId;
            return users;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid userId
        {
            get
            {
                return _userId;
            }
            set
            {
                if (_userId != value)
                {
                    OnuserIdChanging(value);
                    ReportPropertyChanging("userId");
                    _userId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("userId");
                    OnuserIdChanged();
                }
            }
        }
        private global::System.Guid _userId;
        partial void OnuserIdChanging(global::System.Guid value);
        partial void OnuserIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String username
        {
            get
            {
                return _username;
            }
            set
            {
                OnusernameChanging(value);
                ReportPropertyChanging("username");
                _username = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("username");
                OnusernameChanged();
            }
        }
        private global::System.String _username;
        partial void OnusernameChanging(global::System.String value);
        partial void OnusernameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String password
        {
            get
            {
                return _password;
            }
            set
            {
                OnpasswordChanging(value);
                ReportPropertyChanging("password");
                _password = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("password");
                OnpasswordChanged();
            }
        }
        private global::System.String _password;
        partial void OnpasswordChanging(global::System.String value);
        partial void OnpasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String firstname
        {
            get
            {
                return _firstname;
            }
            set
            {
                OnfirstnameChanging(value);
                ReportPropertyChanging("firstname");
                _firstname = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("firstname");
                OnfirstnameChanged();
            }
        }
        private global::System.String _firstname;
        partial void OnfirstnameChanging(global::System.String value);
        partial void OnfirstnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String lastname
        {
            get
            {
                return _lastname;
            }
            set
            {
                OnlastnameChanging(value);
                ReportPropertyChanging("lastname");
                _lastname = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("lastname");
                OnlastnameChanged();
            }
        }
        private global::System.String _lastname;
        partial void OnlastnameChanging(global::System.String value);
        partial void OnlastnameChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LisaKatherineModel", "FK_tblArticle_tblUsers", "tblArticle")]
        public EntityCollection<Articles> tblArticles
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Articles>("LisaKatherineModel.FK_tblArticle_tblUsers", "tblArticle");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Articles>("LisaKatherineModel.FK_tblArticle_tblUsers", "tblArticle", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LisaKatherineModel", "FK_tblPhotos_tblUsers", "tblPhotos")]
        public EntityCollection<Photos> tblPhotos
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Photos>("LisaKatherineModel.FK_tblPhotos_tblUsers", "tblPhotos");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Photos>("LisaKatherineModel.FK_tblPhotos_tblUsers", "tblPhotos", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
